# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 849beace52beb673b43861d80d9fe958d36b1cfa6062fb7e3e407b5eb22cefb2ffdc769994b0115925873690db492390f641fedf3ae6518514156d6afd76d1fe

test:
  secret_key_base: cb1ab2e227cb73a19d8ee9c4d5537768b3b1c94f40a108cf114e84787ecf724965a1a5143558fe9c0eac1c5de9d532b1a79df8de1dd5277ffde6f5b5daddf2c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
